Assignment3:QNode Program Order Queue main
	g++ QNode.o Program.o Order.o Queue.o main.o -o Assignment3
QNode:
	g++ -std=c++11 -c QNode.cpp -o QNode.o 
Program:
	g++ -std=c++11 -c Program.cpp -o Program.o
Order:
	g++ -std=c++11 -c Order.cpp -o Order.o
Queue:
	g++ -std=c++11 -c Queue.cpp -o Queue.o
main:
	g++ -std=c++11 -c main.cpp -o main.o